### PR TITLE
Features/148 better email extraction

### PR DESCRIPTION
**Pull request by crankycoder**
Fixes #148 by addding support to run phantomjs in a subprocess to extract email addresses.

### CODE REVIEW

**Comment by kynan** [comment]
What exactly is the reason the page needs to be pulled down with PhantomJS instead of a simple `urllib2.urlopen`?

**Comment by crankycoder** [comment]
This patch defeats javascript obfuscation and works on sites other than
PLOS.

**Comment by kynan** [comment]
OK, I figured the reason might be JavaScript obfuscation of email addresses. Supposedly you could do the scraping also with PhantomJS and only return the email addresses, no?

**Comment by crankycoder** [comment]
You probably could, there's not much value in doing that though.  You'd
just be introducing yet another regex syntax as Javascript's regex engine
isn't quite the same as Python's.  I also don't feel like implementing
urlparse in Javascript.

**Pull request merged**
