### PR TITLE
google maps sometimes returns NO RESULTS FOUND

### PR DESCRIPTION
**Pull request by kynan**
This causes the lat/long calculation to fail.

### CODE REVIEW

**Comment by kynan** [comment]
The real fix for this would be to prompt the user again, no?

**Comment by crankycoder** [comment]
Geocoding may fail for any number of reasons.  Map server failure,  privacy
settings,  missing data.

We need a reasonable fall back plan.

**Comment by kynan** [comment]
This already deals with the case of nonsense data and is _way_ better than what we do right now.

**Comment by crankycoder** [comment]
Yep.  Sorry,  made the comment before I actually tested.   Fix is good..

**Comment by kynan** [comment]
It's only a start though, it doesn't address all issues e.g. dealing gracefully with the fact that the AJAX call might fail (which is not unlikely given the rate limit).

**Comment by kynan** [comment]
I'll merge this now. This is only a first step, but still way better than hitting loads of paywalls somwhere in the Atlantic.

**Pull request merged**
