### PR TITLE
Remember the user's details

### PR DESCRIPTION
**Pull request by hubgit**
Store the input data (name, profession) in localStorage, if available.

Note: if third-party data storage has been blocked by the user, localStorage (and cookies) isn't available in an iframe. May want to consider opening in a pop-up window instead.

### CODE REVIEW

**Comment by andylolz** [comment]
Interesting… I hadn’t considered doing this in this way! Did you consider using a cookie instead? What do you think?

I’ve added a bit more text to #2. I think this pull request still adds a useful feature for people who don’t want to create a user account, though. I’ll have a little test of it this evening.

**Comment by hubgit** [comment]
It's very similar to using a cookie, but the information is only needed client-side, so there's no need to create a cookie and send it over the network.

**Comment by andylolz** [comment]
Sure, that’s certainly an advantage. One advantage of cookies is they’re more widely supported… But I certainly wouldn’t want a cookie notice on the sidebar!

Anyway – I do like this approach. I’m not really keen on the popup idea – I really like it in a sidebar!

**Comment by hubgit** [comment]
localStorage is available in pretty much everything from IE8 onwards, so is usually fine; it's more likely that people  (especially people who use this bookmarklet) will have third-party data/cookies blocked than not have localStorage, I reckon.

**Comment by andylolz** [comment]
Ok ace. Let’s stick with local storage then :)

I need to find out about getting you commit access, @hubgit!

**Comment by andylolz** [comment]
Manually merged

**Pull request closed without merging**
