### PR TITLE
Add hostname to bookmarklet code

### PR DESCRIPTION
**Pull request by andylolz**
fixes #71

### CODE REVIEW

**Comment by crankycoder** [comment]
Resolved in the django branch as of 1e27808225ab60390c89772672adc0a014bc338b

Note that this uses the Postgresql database and expects that the Site object has been set properly.

**Comment by kynan** [comment]
I don't think 1e27808 resolves all the issues addressed by this pull request. It doesn't do the right thing on localhost by default.

**Comment by crankycoder** [comment]
@kynan you need to be clearer. What doesn't do the right thing?  This works for me and tests are passing. I'm closing this until there is a testcase that demonstrates failure.

**Comment by andylolz** [comment]
This pull request is just suggesting we set the hostname with an environment variable. The `features/mongoengine` branch uses this method.

**Pull request closed without merging**
