### PR TITLE
Add map marker clustering

### PR DESCRIPTION
**Pull request by andylolz**
Fixes #9.

### CODE REVIEW

**Comment by andylolz** [comment]
This isn’t _quite_ ready to merge yet
- [x] we need our nice custom markers
- [ ] we should think about clustering server side (although probably not for MVP)
- [x] zooming is a bit odd – some map settings probably need tweaking

**Comment by andylolz** [comment]
Note that this code also switches from gmaps to OSM, which fixes #44.

**Comment by andylolz** [comment]
I reckon it’s good to go now. Someone please review / approve :)

**Comment by kynan** [comment]
Can we not load `leaflet.markercluster` from a CDN? Or at least use the minified version?

**Update:** seems that's not available on any CDN afaict.

**Comment by crankycoder** [comment]
We could push this up to a CDN like Cloudfront, but I'm pretty skeptical that many people actually have leaflet pre-loaded in their browser cache.  I've updated the template and js to use the minified version for the leaflet.marketcluster repo though.

**Comment by crankycoder** [comment]
Just a side note - the leaflet.marketCluster-src.js file didn't seem to minify with the closure compiler which makes me worry a bit.

**Comment by andylolz** [comment]
Hmm that is weird… What did you minify with in the end, @crankycoder?

**Comment by crankycoder** [comment]
I just pulled in the minified JS from the leaflet.markerCluster project that they had in github.

**Comment by andylolz** [comment]
Aha! Very good plan.

**Pull request merged**
