### PR TITLE
Features/mongoengine

### PR DESCRIPTION
**Pull request by crankycoder**
This is quite a few changes.

I've ported to using MongoEngine.

The bookmarklet on the front page does not appear by default anymore.

On login, you'll now get a dialog popup and the bookmarklet link will show up on the front page.

Users are all stored in mongo using mongoengine.

Duplicate logins are special cased - you just get the first login information.

Custom bookmarklet per user works.  

Added mongodb to the travis services so that tests run against a real mongodb instance now.

I haven't tested this on heroku.

### CODE REVIEW

**Comment by andylolz** [comment]
Haha wow – this looks epic. Ok, let me give this a test

**Comment by loleg** [comment]
Sign up is not working yet, I take it users are created with Django admin for now?

**Comment by crankycoder** [comment]
Users get created in the fly with the form.  Or at least they should.

I'll add a test to clarify this.

**Comment by crankycoder** [comment]
https://github.com/OAButton/OAButton/blob/features/mongoengine/oabutton/apps/bookmarklet/views.py

Has a signin method.  On failure to find the user by email address,  I create a new one.

**Comment by loleg** [comment]
Oh, right, that works. I was talking about http://localhost:8000/#get-it which gives a 404 on the POST to `/api/signup`

**Comment by crankycoder** [comment]
Where is that being called?   I really need to use named url lookups.  Bah.

**Comment by andylolz** [comment]
d717c6e should fix that issue, @loleg. I’ve [deployed to heroku here](https://oabutton-django.herokuapp.com/), but the json doesn’t look quite right so the map isn’t showing up yet.

This is really great, @crankycoder – well done for getting it all sorted! In this case, it would have been preferable to create a mongoengine issue, and do a separate pull request for that, just so this one wasn’t quite so epic. But that is a minor gripe, and let’s not let it detract from the awesomeness of this.

I think there are still some minor bits and bobs to sort here, but let’s merge to `develop` once the map is working again on heroku.

**Comment by crankycoder** [comment]
The serialization change is probably the problem.  It's working over here
on my local rig, I'll take a look tonight and try to redeploy.

**Comment by andylolz** [comment]
Ah! Apologies – My mistake regarding serializing. [That has fixed it!](http://oabutton-django.herokuapp.com/)

So… Push the button whenever you’re happy, @crankycoder. Looks fine to me.

**Comment by crankycoder** [comment]
@loleg Regarding: https://github.com/OAButton/OAButton/pull/105#issuecomment-25920338

I only see the #get-it link on the frontpage as a link to the login form where the user gets the bookmarklet.  I can't see any case where someone might POST to that hyperlink you're mentioning.

**Pull request merged**
