### PR TITLE
Fix equality-checking bugs

### PR DESCRIPTION
**Pull request by diracdeltas**

### CODE REVIEW

**Comment by hubgit** [comment]
The "equality checking" in the `if` statements is actually assignment to a variable, so this change would cause problems. Apologies if that's confusing - feel free to move the assignment out of the `if` statement if it will be clearer.

**Comment by diracdeltas** [comment]
Gotcha, thanks!

**Comment by diracdeltas** [comment]
@hubgit Doesn't `doi_re.exec(childNode.nodeValue)` always return a value that is type-converted to true? If the regex doesn't match, it returns [""]. If the intent is to return the first match only if a non-empty match is found, then you want 

`if (matches = doi_re.exec(childNode.nodeValue)[0])`

**Comment by hubgit** [comment]
`RegExp.exec(string)` returns an array if it matches, and null if it doesn't:

```
/x/.exec("example")
=> ["x"]

/y/.exec("example")
=> null
```

**Comment by diracdeltas** [comment]
Oops, you're right! My bad.

**Pull request closed without merging**
