### PR TITLE
Updated logo colour and added vector version closes #88

### PR DESCRIPTION
**Pull request by tompollard**

### CODE REVIEW

**Comment by andylolz** [comment]
haha awesome!

**Comment by andylolz** [comment]
I suspect we might need a version with a transparent background… @JosephMcArthur have you had a look at this? If you click on the commit above, you can see the image

**Comment by kynan** [comment]
True, the PNG definitely needs a transparent background.

**Comment by andylolz** [comment]
I thiiiiink the 'o' inside the lock should be white (rather than transparent)… Is that possible to fix? Sorry to be picky!

**Comment by tompollard** [comment]
Hi Andy,

I have updated the logo as suggested. Probably a mess of the pull request, so let me know if the changes don't show up on your side!

Tom

**Comment by andylolz** [comment]
Perfect! Thanks @tompollard

**Pull request merged**
