### PR TITLE
Add a Google Scholar title search after submission

### PR DESCRIPTION
**Pull request by jezcope**
Addresses #68, and also moves the PMC link to appear after submission of the form, as per #39.

### CODE REVIEW

**Comment by kynan** [comment]
I think this looks good!

**Comment by crankycoder** [comment]
Is anything blocking the merge here?

**Comment by kynan** [comment]
Bump! Do we still want this? It will need rebasing before merge.

**Comment by JosephMcArthur** [comment]
As I understand it (and I'm not 100% sure I do) it's not MVP, what we had
after the hackday was okay.

But if it's quick to merge in then sure.

**Comment by crankycoder** [comment]
This is already merged in with the core code in #101

**Pull request closed without merging**
