### PR TITLE
Banner should not obscure map

### PR DESCRIPTION
**Pull request by kynan**
Currently, the banner at
https://www.openaccessbutton.org/#world
obscures large parts of the southern hemisphere when viewed at the default resolution. 
Please move away, preferably such that it does not overlap with map or at least can be moved around or clicked away easily.

### CODE REVIEW

**Comment by davidecarroll** [comment]
Quite a few people have emailed about this. Would it be able to increase the height of the map so that the banner fits over Antarctica @loleg?

**Comment by loleg** [comment]
Thanks for taking care of this @kynan

**Comment by andylolz** [comment]
I’m with @Daniel-Mietchen on this. It’s not just the problem at default resolution, though. Often when you click a cluster, it expands, and some points disappear under the banner.

Couldn’t the banner just be below the map?

**Comment by loleg** [comment]
@kynan @davidecarroll I've moved the banner underneath, made the map more responsive, and added custom colours to the main buttons (green sign in, orange bookmarklet) & shadows to the contribution buttons.

**Comment by kynan** [comment]
This branch needs rewriting and stripping of all the commits that cancel each other. Will do that now.

**Comment by crankycoder** [comment]
I've restored the branch. This should never have been merged - tests were failing and JS is broken.

**Comment by kynan** [comment]
@crankycoder This doesn't even touch any JavaScript!

**Comment by jalperin** [comment]
@kynan: not that i've even looked at the code, but quite often JS and CSS are very intertwined, as often CSS selectors are in the JS

**Pull request merged**
