### PR TITLE
Fetch metadata from CrossRef

### PR DESCRIPTION
**Pull request by hubgit**
Rewrote some of the existing JS in one commit before adding the CrossRef code - hope that's ok, can split into two pull requests if preferred.

### CODE REVIEW

**Comment by andylolz** [comment]
The cleanup looks great. I’m excited to test out the metadata fetch! Excellent feature! :+1:

**Comment by andylolz** [comment]
Ah that is awesome! Love it.

I think the Event model also needs modifying in order to store the description in the db. I think it’s just:

```
  description: String
```

Do you fancy adding that to this pull request? I’m not sure how I add commits to your pull request, and it’s tidier that way than merging and then adding commits.

**Comment by hubgit** [comment]
Added the "description" property, and also added some field names to each line of the description, so that they can be parsed out later (e.g. journal name).

**Comment by andylolz** [comment]
Ah – Very good point! Thanks for this

**Comment by andylolz** [comment]
Merged manually. This is awesome work!

**Pull request closed without merging**
