### PR TITLE
GET request to http://www.openaccessbutton.org/api/form/page2/ sent over clear HTTP

### PR DESCRIPTION
**Pull request by kynan**
Should be HTTPS like the rest of the requests, especially since it contains the CSRF token.

### CODE REVIEW

**Comment by kynan** [comment]
Where is this request made from?

**Comment by diracdeltas** [comment]
@kynan after making the submission POST from the bookmarklet. I'm using the latest bookmarklet from openaccessbutton.org.

**Comment by kynan** [comment]
@diracdeltas Thanks, great catch!

@crankycoder Is this good to merge?

**Comment by crankycoder** [comment]
@kynan I ended up needing another proxy for crossref.org. Code is in 90e4cd1e341141ec88117b311fefaf410873d320

**Pull request merged**
