### PR TITLE
Rewrite bookmarklet to not depend on jQuery

### PR DESCRIPTION
**Pull request by hubgit**
Also adds DOI detection.

### CODE REVIEW

**Comment by andylolz** [comment]
Ah ace! Yeah I actually added jquery to a working non-jquery version: d277c2d because I thought it would help with DOI detection, and then after doing it realised it wouldn’t at all! Far better to avoid it.

Anyway – awesome. Thanks for this! Just glanced over it and all looks great. We discussed a very similar (but slightly more general) DOI approach – looking for metadata with a name ending: `_doi` first before regexing. What do you think?

**Comment by hubgit** [comment]
I like the assurance that if there is a `meta[name='citation_doi']` then it's definitely the DOI of the article, for the first test.

A test for `meta[name$='_doi']` could be added as a second step, though. It would be nice to have a set of article HTML from all publishers, to see exactly what properties that would match...

**Comment by andylolz** [comment]
Yep absolutely. We had a search about on saturday and found there is no standard for the metadata naming – every journal does it slightly differently (although the _doi suffix is reasonably consistent).

However, tools like [mendeley](www.mendeley.com) and [zotero](www.zotero.org) are really good at:
1. spotting you’re on a journal page, and
2. reading this metadata

so maybe there is a handy database / api / bit of code for solving this problem. We’ve been in touch with zotero with some help solving this, and related issues!

**Comment by hubgit** [comment]
All the `citation_*` fields are usually consistent (if they're present), as they're what Google Scholar uses for indexing. Anything else can vary wildly, as you've found :-)

**Comment by andylolz** [comment]
Aha! I didn’t realise google scholar used those – good to know!

**Comment by hubgit** [comment]
There's some related code for detecting PDF URLs and reading `citation_*` meta elements in https://github.com/hubgit/save-to-appdotnet/blob/gh-pages/chrome/extract.js if that's any use to you (and I need to port this detectDOI method back to there).

**Comment by andylolz** [comment]
Aha – You are experienced in these matters, @hubgit! Thanks for this, I’ll take a look!

**Pull request merged**
