### PR TITLE
Improve CrossRef lookup

### PR DESCRIPTION
**Pull request by hubgit**
Use the application/vnd.citationstyles.csl+json format instead of
application/json, as it's easier to parse and more reliable

### CODE REVIEW

**Comment by kynan** [comment]
Why was this not merged but just closed?

**Comment by hubgit** [comment]
Looks like it was closed accidentally as a possible node-related issue - I'll re-open.

**Comment by kynan** [comment]
@hubgit Could you rebase on `develop`?

**Comment by hubgit** [comment]
Rebased.

**Comment by kynan** [comment]
Would you mind doing an actual rebase rather than a merge from upstream (just to keep history a bit cleaner)?

**Comment by crankycoder** [comment]
Sorry - I completely missed this.

**Pull request merged**
